name: CI

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Zip
        uses: TheDoctor0/zip-release@0.6.0
        with:
          filename: woocommerce_coolrunner.zip
          directory: coolrunner-shipping-plugin

      - name: Upload release asset
        uses: alexellis/upload-assets@0.3.0
        with:
          asset_paths:
            - 'woocommerce_coolrunner.zip'
